name: build-vcpkg-cache

on:
  workflow_dispatch:
  push:
    paths:
      - vcpkg.json
      - vcpkg-configuration.json
      - .github/workflows/build-vcpkg.yml

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: windows-2022

    strategy:
      fail-fast: false
      matrix:
        triplet:
          - x64-windows
          - x64-windows-static

    env:
      VCPKG_ROOT: C:\vcpkg
      FEED_URL: https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json
      VCPKG_BINARY_SOURCES: clear;nuget,https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json,readwrite

    steps:
      - uses: actions/checkout@v4

      - name: Check vcpkg
        shell: pwsh
        run: |
          & "${env:VCPKG_ROOT}\vcpkg.exe" version

      - name: Add GitHub Packages NuGet source
        shell: pwsh
        run: |
          dotnet nuget add source "${env:FEED_URL}" `
            --name "github" `
            --username "${{ github.actor }}" `
            --password "${{ secrets.GITHUB_TOKEN }}" `
            --store-password-in-clear-text

      - name: Install dependencies with vcpkg
        shell: pwsh
        run: |
          & "${env:VCPKG_ROOT}\vcpkg.exe" install `
            --triplet "${{ matrix.triplet }}" `
            --x-manifest-root="${{ github.workspace }}" `
            --clean-buildtrees-after-build